/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joptionpane;
import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class Interfaz extends javax.swing.JFrame {
  static boolean VD;
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Classes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Mana = new javax.swing.JButton();
        Rareza = new javax.swing.JButton();
        Tipo = new javax.swing.JButton();
        Ataque = new javax.swing.JButton();
        Vida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Classes.setText("Classes");
        Classes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesActionPerformed(evt);
            }
        });

        jLabel1.setText("Todas las classes");

        Mana.setText("Coste de mana");
        Mana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManaActionPerformed(evt);
            }
        });

        Rareza.setText("Rareza");
        Rareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RarezaActionPerformed(evt);
            }
        });

        Tipo.setText("Tipo de carta");
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });

        Ataque.setText("Ataque");
        Ataque.setToolTipText("");
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });

        Vida.setText("Vida");
        Vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaActionPerformed(evt);
            }
        });

        jLabel2.setText("0+");

        jLabel3.setText("Comun, incomun");

        jLabel4.setText("Cualquier tipo");

        jLabel5.setText("0,1...");

        jLabel6.setText("0,1...");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setText("Filtros cartas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ataque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rareza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Classes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Classes)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mana)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rareza)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ataque)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vida)
                    .addComponent(jLabel6))
                .addGap(86, 86, 86))
        );

        Classes.getAccessibleContext().setAccessibleName("Classes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassesActionPerformed
       String[] classes={"Todas las Classes", "Caballero de la muerte", "Cazador de Demonios", "Druida", "Cazador", "Mago", "Paladin","Clerigo","Asesino"};
       
      String opcion= (String)JOptionPane.showInputDialog(null, "Indica la classe de la carta: ","Classes",
               JOptionPane.PLAIN_MESSAGE ,null, classes,classes[0]);
       jLabel1.setText(opcion);
    }//GEN-LAST:event_ClassesActionPerformed

    private void ManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManaActionPerformed
        String[] mana={"0","1","2","3","4","5","6","7","8","9","10"};
        String opcionM=(String) JOptionPane.showInputDialog(null, "Indica la cantidad de mana: ","Mana",
               JOptionPane.PLAIN_MESSAGE ,null, mana ,mana[0]);
        jLabel2.setText(opcionM);
    }//GEN-LAST:event_ManaActionPerformed

    private void RarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RarezaActionPerformed
        String[] rareza={"Cualquiera","Comun","Rara","Epica","Legendaria"};
        String opcionR=(String) JOptionPane.showInputDialog(null, "Indica la rareza de la carta: ","Rareza",
               JOptionPane.PLAIN_MESSAGE ,null, rareza ,rareza[0]);
        jLabel3.setText(opcionR);
    }//GEN-LAST:event_RarezaActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        String[] tipo={"Cualquiera","Heroe","Minion","Hechizo","Arma","Lugar"};
        String opcionT=(String) JOptionPane.showInputDialog(null, "Indica el tipo de la carta: ","Tipo de cartas",
               JOptionPane.PLAIN_MESSAGE ,null, tipo ,tipo[0]);
        jLabel4.setText(opcionT);
        if (opcionT.equals("Hechizo")) {
            VD=false;
        }else{
            VD=true;
        }
    }//GEN-LAST:event_TipoActionPerformed

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        if (VD!=false) {
            String[] ataque={"Cualquiera","0","1","2","3","4","5","6","7","8","9","10+"};
            String opcionA=(String) JOptionPane.showInputDialog(null, "Indica el ataque de la carta: ","Ataque",
               JOptionPane.PLAIN_MESSAGE ,null, ataque ,ataque[0]);
            jLabel5.setText(opcionA);
        }else{
            JOptionPane.showMessageDialog(null, "Un hechizo no puede tener ni ataque ni vida", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_AtaqueActionPerformed

    private void VidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaActionPerformed
       if (VD!=false) {
            String[] Vida={"Cualquiera","0","1","2","3","4","5","6","7","8","9","10+"};
            String opcionV=(String) JOptionPane.showInputDialog(null, "Indica el ataque de la carta: ","Ataque",
               JOptionPane.PLAIN_MESSAGE ,null, Vida ,Vida[0]);
            jLabel6.setText(opcionV);
        }else{
            JOptionPane.showMessageDialog(null, "Un hechizo no puede tener ni ataque ni vida", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_VidaActionPerformed

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ataque;
    private javax.swing.JButton Classes;
    private javax.swing.JButton Mana;
    private javax.swing.JButton Rareza;
    private javax.swing.JButton Tipo;
    private javax.swing.JButton Vida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
